### ISSUE TITLE
Fix SSL Certificate to puma.io

### ISSUE THREAD

**Issue by stoivo** [puma/puma.io#17]

**Comment by dentarg** [comment]
This should now be possible to solve with GitHub Pages cc @evanphx 

https://github.blog/2018-05-01-github-pages-custom-domains-https/
https://help.github.com/en/articles/using-a-custom-domain-with-github-pages

**Comment by nateberkopec** [comment]
<img width="177" alt="Screen Shot 2019-08-06 at 9 57 48 AM" src="https://user-images.githubusercontent.com/845662/62559868-af453480-b830-11e9-92f5-5a13436af550.png">

seems good now
