### ISSUE TITLE
query on competitor speed comparison parameters

### ISSUE THREAD

**Issue by damned** [puma/puma.io#67]
hi there,

apologies if this is obvious to others but what do the:

16:16
1x16
16x32

parameters on the [speed comparison](https://puma.io/#speed-comparison) candidates refer to?

**Comment by nateberkopec** [comment]
Thanks for your question - sorry, that comparison is at least 10 years old, so it should probably just be removed at this point.

It refers to the thread/worker configuration. When talking about puma, we're talking about `min_threads:max_threads`. It's possible Evan ran these benchmarks even on Rubinius, I'm not sure.

I think the Rainbows numbers are `thread_countxworker_count`.
